// <auto-generated />
using System;
using FerieRegistreringBackend.Repository.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FerieRegistreringBackend.API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FerieRegistreringBackend.Repository.Models.TimeEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TimeEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2025, 8, 20),
                            Description = "Almindelig arbejdsdag",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2025, 8, 21),
                            Description = "Tidlig fri",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2025, 8, 22),
                            Description = "Konference dag",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2025, 8, 23),
                            Description = "Projektarbejde",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 30, 0, 0),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2025, 8, 24),
                            Description = "Halv dag",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2025, 8, 25),
                            Description = "Almindelig arbejdsdag",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2025, 8, 26),
                            Description = "Halv dag",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2025, 8, 27),
                            Description = "Skiftehold",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2025, 8, 28),
                            Description = "Kontorarbejde",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2025, 8, 29),
                            Description = "Sen vagt",
                            EndTime = new TimeSpan(0, 19, 0, 0, 0),
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2025, 8, 30),
                            Description = "Projektarbejde",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2025, 8, 31),
                            Description = "Halv dag",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2025, 9, 1),
                            Description = "Tidlig start",
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            StartTime = new TimeSpan(0, 7, 30, 0, 0),
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2025, 9, 2),
                            Description = "Almindelig arbejdsdag",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2025, 9, 3),
                            Description = "Møde dag",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2025, 9, 4),
                            Description = "Kort dag",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2025, 9, 5),
                            Description = "Kursus",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2025, 9, 6),
                            Description = "Projektarbejde",
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            StartTime = new TimeSpan(0, 9, 30, 0, 0),
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2025, 9, 7),
                            Description = "Halv dag",
                            EndTime = new TimeSpan(0, 13, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2025, 9, 8),
                            Description = "Almindelig arbejdsdag",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2025, 9, 9),
                            Description = "Supportarbejde",
                            EndTime = new TimeSpan(0, 16, 30, 0, 0),
                            StartTime = new TimeSpan(0, 8, 30, 0, 0),
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2025, 9, 10),
                            Description = "Halv dag",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2025, 9, 11),
                            Description = "Kursusdag",
                            EndTime = new TimeSpan(0, 15, 30, 0, 0),
                            StartTime = new TimeSpan(0, 7, 30, 0, 0),
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2025, 9, 12),
                            Description = "Almindelig arbejdsdag",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2025, 9, 13),
                            Description = "Mødedag",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2025, 9, 14),
                            Description = "Projektarbejde",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 26
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2025, 9, 15),
                            Description = "Halv dag",
                            EndTime = new TimeSpan(0, 14, 0, 0, 0),
                            StartTime = new TimeSpan(0, 8, 0, 0, 0),
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2025, 9, 16),
                            Description = "Skiftehold",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            StartTime = new TimeSpan(0, 7, 0, 0, 0),
                            UserId = 28
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2025, 9, 17),
                            Description = "Kontorarbejde",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            UserId = 29
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2025, 9, 18),
                            Description = "Kontorarbejde",
                            EndTime = new TimeSpan(0, 17, 0, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            UserId = 29
                        });
                });

            modelBuilder.Entity("FerieRegistreringBackend.Repository.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateOnly(1995, 5, 12),
                            Email = "niklas@example.com",
                            LastName = "Hansen",
                            Name = "Niklas",
                            Password = "test123"
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateOnly(1980, 5, 19),
                            Email = "frygtsommehund@example.com",
                            LastName = "Hund",
                            Name = "Frygtløss",
                            Password = "password"
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateOnly(1956, 5, 12),
                            Email = "homer.simpson@springfield.com",
                            LastName = "Simpson",
                            Name = "Homer",
                            Password = "donuts"
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateOnly(1966, 7, 1),
                            Email = "peter.griffin@quahog.com",
                            LastName = "Griffin",
                            Name = "Peter",
                            Password = "lois123"
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateOnly(1999, 5, 1),
                            Email = "patrick.star@bikinibottom.com",
                            LastName = "Star",
                            Name = "Patrick",
                            Password = "mayoi"
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateOnly(2005, 3, 9),
                            Email = "lisa.simpson@springfield.com",
                            LastName = "Simpson",
                            Name = "Lisa",
                            Password = "saxophone"
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateOnly(1960, 10, 1),
                            Email = "marge.simpson@springfield.com",
                            LastName = "Simpson",
                            Name = "Marge",
                            Password = "bluehair"
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateOnly(2018, 7, 14),
                            Email = "stewie.griffin@quahog.com",
                            LastName = "Griffin",
                            Name = "Stewie",
                            Password = "worlddomination"
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateOnly(2010, 11, 2),
                            Email = "brian.griffin@quahog.com",
                            LastName = "Griffin",
                            Name = "Brian",
                            Password = "martini"
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateOnly(1990, 6, 18),
                            Email = "sandy.cheeks@bikinibottom.com",
                            LastName = "Cheeks",
                            Name = "Sandy",
                            Password = "karate"
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateOnly(1982, 4, 10),
                            Email = "squidward@bikinibottom.com",
                            LastName = "Tentacles",
                            Name = "Squidward",
                            Password = "clarinet"
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateOnly(1970, 7, 5),
                            Email = "mr.krabs@bikinibottom.com",
                            LastName = "Krabs",
                            Name = "Mr",
                            Password = "money"
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateOnly(1972, 8, 22),
                            Email = "plankton@bikinibottom.com",
                            LastName = "Plankton",
                            Name = "Sheldon",
                            Password = "chumbucket"
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateOnly(2007, 4, 1),
                            Email = "bart.simpson@springfield.com",
                            LastName = "Simpson",
                            Name = "Bart",
                            Password = "eatmyshorts"
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateOnly(2003, 8, 21),
                            Email = "meg.griffin@quahog.com",
                            LastName = "Griffin",
                            Name = "Meg",
                            Password = "ignored"
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateOnly(1975, 3, 3),
                            Email = "lois.griffin@quahog.com",
                            LastName = "Griffin",
                            Name = "Lois",
                            Password = "familyfirst"
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateOnly(2001, 2, 12),
                            Email = "chris.griffin@quahog.com",
                            LastName = "Griffin",
                            Name = "Chris",
                            Password = "artsy"
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateOnly(1965, 2, 9),
                            Email = "ned.flanders@springfield.com",
                            LastName = "Flanders",
                            Name = "Ned",
                            Password = "okelydokely"
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateOnly(1963, 11, 5),
                            Email = "moe.szyslak@springfield.com",
                            LastName = "Szyslak",
                            Name = "Moe",
                            Password = "bar123"
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateOnly(1970, 4, 14),
                            Email = "carl.carlson@springfield.com",
                            LastName = "Carlson",
                            Name = "Carl",
                            Password = "powerplant"
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateOnly(1970, 6, 6),
                            Email = "lenny.leonard@springfield.com",
                            LastName = "Leonard",
                            Name = "Lenny",
                            Password = "duffbeer"
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateOnly(1930, 9, 15),
                            Email = "mr.burns@springfield.com",
                            LastName = "Burns",
                            Name = "Mr",
                            Password = "excellent"
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateOnly(1968, 7, 30),
                            Email = "smithers@springfield.com",
                            LastName = "Smithers",
                            Name = "Waylon",
                            Password = "loyal"
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateOnly(2012, 2, 14),
                            Email = "ralph.wiggum@springfield.com",
                            LastName = "Wiggum",
                            Name = "Ralph",
                            Password = "choochoo"
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateOnly(1971, 12, 7),
                            Email = "apu@springfield.com",
                            LastName = "Nahasapeemapetilon",
                            Name = "Apu",
                            Password = "kwikemart"
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateOnly(2006, 7, 1),
                            Email = "milhouse@springfield.com",
                            LastName = "Van Houten",
                            Name = "Milhouse",
                            Password = "bestfriend"
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateOnly(1975, 1, 1),
                            Email = "comic.bookguy@springfield.com",
                            LastName = "Book Guy",
                            Name = "Comic",
                            Password = "worstpasswordever"
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateOnly(1960, 11, 1),
                            Email = "edna.krabappel@springfield.com",
                            LastName = "Krabappel",
                            Name = "Edna",
                            Password = "teacher"
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateOnly(1961, 5, 30),
                            Email = "seymour.skinner@springfield.com",
                            LastName = "Skinner",
                            Name = "Principal",
                            Password = "discipline"
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateOnly(1962, 6, 1),
                            Email = "willie@springfield.com",
                            LastName = "Willie",
                            Name = "Groundskeeper",
                            Password = "scotland"
                        });
                });

            modelBuilder.Entity("FerieRegistreringBackend.Repository.Models.Vacation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vacations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateOnly(2025, 7, 14),
                            IsApproved = true,
                            Reason = "Sommerferie",
                            StartDate = new DateOnly(2025, 7, 1),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateOnly(2025, 3, 7),
                            IsApproved = false,
                            Reason = "Sygdom",
                            StartDate = new DateOnly(2025, 3, 3),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateOnly(2025, 9, 12),
                            IsApproved = true,
                            Reason = "Konference",
                            StartDate = new DateOnly(2025, 9, 10),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateOnly(2026, 1, 2),
                            IsApproved = true,
                            Reason = "Juleferie",
                            StartDate = new DateOnly(2025, 12, 20),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateOnly(2025, 5, 20),
                            IsApproved = true,
                            Reason = "Strandferie",
                            StartDate = new DateOnly(2025, 5, 15),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            EndDate = new DateOnly(2025, 10, 5),
                            IsApproved = true,
                            Reason = "Barsel",
                            StartDate = new DateOnly(2025, 10, 1),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            EndDate = new DateOnly(2025, 4, 12),
                            IsApproved = true,
                            Reason = "Forårsferie",
                            StartDate = new DateOnly(2025, 4, 8),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            EndDate = new DateOnly(2025, 2, 25),
                            IsApproved = false,
                            Reason = "Skiferie",
                            StartDate = new DateOnly(2025, 2, 20),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            EndDate = new DateOnly(2025, 6, 7),
                            IsApproved = true,
                            Reason = "Personlige årsager",
                            StartDate = new DateOnly(2025, 6, 1),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            EndDate = new DateOnly(2025, 11, 14),
                            IsApproved = true,
                            Reason = "Efterårsferie",
                            StartDate = new DateOnly(2025, 11, 10),
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            EndDate = new DateOnly(2025, 8, 15),
                            IsApproved = true,
                            Reason = "Sommerferie",
                            StartDate = new DateOnly(2025, 8, 1),
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            EndDate = new DateOnly(2025, 1, 9),
                            IsApproved = false,
                            Reason = "Sygdom",
                            StartDate = new DateOnly(2025, 1, 5),
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            EndDate = new DateOnly(2025, 9, 25),
                            IsApproved = true,
                            Reason = "Bryllup",
                            StartDate = new DateOnly(2025, 9, 20),
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            EndDate = new DateOnly(2025, 12, 30),
                            IsApproved = true,
                            Reason = "Juleferie",
                            StartDate = new DateOnly(2025, 12, 22),
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            EndDate = new DateOnly(2025, 5, 15),
                            IsApproved = true,
                            Reason = "Familiebesøg",
                            StartDate = new DateOnly(2025, 5, 10),
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            EndDate = new DateOnly(2025, 3, 18),
                            IsApproved = false,
                            Reason = "Sygdom",
                            StartDate = new DateOnly(2025, 3, 14),
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            EndDate = new DateOnly(2025, 6, 28),
                            IsApproved = true,
                            Reason = "Fødselsdagsrejse",
                            StartDate = new DateOnly(2025, 6, 20),
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            EndDate = new DateOnly(2025, 4, 7),
                            IsApproved = true,
                            Reason = "Påskeferie",
                            StartDate = new DateOnly(2025, 4, 1),
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            EndDate = new DateOnly(2025, 2, 16),
                            IsApproved = true,
                            Reason = "Weekendtur",
                            StartDate = new DateOnly(2025, 2, 14),
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            EndDate = new DateOnly(2025, 11, 5),
                            IsApproved = true,
                            Reason = "Efterårsferie",
                            StartDate = new DateOnly(2025, 11, 1),
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            EndDate = new DateOnly(2025, 7, 25),
                            IsApproved = true,
                            Reason = "Sommerferie",
                            StartDate = new DateOnly(2025, 7, 20),
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            EndDate = new DateOnly(2025, 1, 20),
                            IsApproved = false,
                            Reason = "Sygdom",
                            StartDate = new DateOnly(2025, 1, 15),
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            EndDate = new DateOnly(2025, 9, 9),
                            IsApproved = true,
                            Reason = "Kursus",
                            StartDate = new DateOnly(2025, 9, 5),
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            EndDate = new DateOnly(2026, 1, 1),
                            IsApproved = true,
                            Reason = "Juleferie",
                            StartDate = new DateOnly(2025, 12, 24),
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            EndDate = new DateOnly(2025, 5, 3),
                            IsApproved = true,
                            Reason = "Weekendtur",
                            StartDate = new DateOnly(2025, 5, 1),
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            EndDate = new DateOnly(2025, 3, 25),
                            IsApproved = false,
                            Reason = "Sygdom",
                            StartDate = new DateOnly(2025, 3, 21),
                            UserId = 26
                        },
                        new
                        {
                            Id = 27,
                            EndDate = new DateOnly(2025, 6, 15),
                            IsApproved = true,
                            Reason = "Familieferie",
                            StartDate = new DateOnly(2025, 6, 10),
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            EndDate = new DateOnly(2025, 4, 23),
                            IsApproved = true,
                            Reason = "Påskeferie",
                            StartDate = new DateOnly(2025, 4, 20),
                            UserId = 28
                        },
                        new
                        {
                            Id = 29,
                            EndDate = new DateOnly(2025, 2, 9),
                            IsApproved = true,
                            Reason = "Skiferie",
                            StartDate = new DateOnly(2025, 2, 5),
                            UserId = 29
                        },
                        new
                        {
                            Id = 30,
                            EndDate = new DateOnly(2025, 10, 20),
                            IsApproved = true,
                            Reason = "Efterårsferie",
                            StartDate = new DateOnly(2025, 10, 15),
                            UserId = 30
                        });
                });

            modelBuilder.Entity("FerieRegistreringBackend.Repository.Models.TimeEntry", b =>
                {
                    b.HasOne("FerieRegistreringBackend.Repository.Models.User", "User")
                        .WithMany("TimeEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FerieRegistreringBackend.Repository.Models.Vacation", b =>
                {
                    b.HasOne("FerieRegistreringBackend.Repository.Models.User", "User")
                        .WithMany("Vacations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FerieRegistreringBackend.Repository.Models.User", b =>
                {
                    b.Navigation("TimeEntries");

                    b.Navigation("Vacations");
                });
#pragma warning restore 612, 618
        }
    }
}
